name: flutter_mvvm_boilerplate
description: "A production-ready Flutter boilerplate with Clean MVVM + Feature-First architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dio_smart_retry: ^7.0.1
  equatable: ^2.0.7
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_form_builder: ^10.2.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.1.0
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^4.1.0
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  share_plus: ^10.1.4
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  injectable_generator: ^2.6.3
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
